<?php
namespace Plugins\SiteSEO\Sitemap;
class SitemapParser
{
    private $xml;

    public function __construct($xmlString)
    {
        $this->xml = simplexml_load_string($xmlString);
    }

    public function getUrls()
    {
        $urls = [];
        foreach ($this->xml->url as $url) {
            $urlData = [
                'loc' => (string)$url->loc,
                'changefreq' => (string)$url->changefreq,
                'priority' => (string)$url->priority,
            ];

            // Check if image data is available
            if ($url->image) {
                $imageData = [
                    'image:caption' => (string)$url->image->children('image', true)->caption,
                    'image:loc' => (string)$url->image->children('image', true)->loc,
                ];

                $urlData['image'] = $imageData;
            }

            $urls[] = $urlData;
        }

        return $urls;
    }
}

// // Sample XML string
// $xmlString = '<?xml version="1.0" encoding="UTF-8">
// <!-- Generated by https://git.io/phpseo -->
// <urlset
//     xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
//     xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
//     <url>
//         <loc>https://example.com/blog</loc>
//         <changefreq>daily</changefreq>
//         <priority>0.8</priority>
//     </url>
//     <url>
//         <loc>https://example.com/blog/my-new-article</loc>
//         <changefreq>weekly</changefreq>
//         <lastmod>2019-03-01T00:00:00+01:00</lastmod>
//         <image:image>
//             <image:caption>My caption</image:caption>
//             <image:loc>https://example.com/uploads/image.jpeg</image:loc>
//         </image:image>
//     </url>
// </urlset>';

// // Create an instance of the SitemapParser
// $parser = new SitemapParser($xmlString);

// // Get the URLs and their data
// $urls = $parser->getUrls();

// // Print the results
// foreach ($urls as $urlData) {
//     echo "URL: " . $urlData['loc'] . "\n";
//     echo "Change Frequency: " . $urlData['changefreq'] . "\n";
//     echo "Priority: " . $urlData['priority'] . "\n";

//     if (isset($urlData['image'])) {
//         echo "Image Caption: " . $urlData['image']['image:caption'] . "\n";
//         echo "Image Location: " . $urlData['image']['image:loc'] . "\n";
//     }

//     echo "\n";
// }
